name: cd

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, 'skipci')"
    uses: octue/workflows/.github/workflows/build-octue-service.yml@support-kueue
    permissions:
      id-token: write
      contents: read
    with:
      gcp_project_name: octue-openfast
      gcp_project_number: 86611255144
      gcp_region: europe-west3
      gcp_resource_affix: octue
      gcp_service_name: openfast-service
      local_dockerfile: ./Dockerfile
